export const ActionTypes = {
  SET_DARK_MODE: 'SET_DARK_MODE',
  SET_LOCATION: 'SET_LOCATION',
  SET_CITIES: 'SET_CITIES',
  SET_SELECTED_CITY: 'SET_SELECTED_CITY',
  SET_FIVE_DAY_FORECAST: 'SET_FIVE_DAY_FORECAST',
  SET_AVAILABLE_CITIES: 'SET_AVAILABLE_CITIES',
  ADD_FAVORITE_CITY: 'ADD_FAVORITE_CITY',
  REMOVE_FAVORITE_CITY: 'REMOVE_FAVORITE_CITY',
  ADD_CITY_ID: 'ADD_CITY_ID',
};
