/*** PREFERENCES ACTIONS ***/
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_UNITS = 'SET_UNITS';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export const REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY';

/*** WEATHER ACTIONS ***/

export const SET_CURRENT_LOCATION_WEATHER = 'SET_CURRENT_LOCATION_WEATHER';
export const SET_LOCATION_FORECAST = 'SET_LOCATION_FORECAST';
export const ADD_AVAILABLE_CITY = 'SET_AVAILABLE_CITIES';
export const SET_CURRENT_CITY = 'SET_ID_FROM_LOCATION';
