/*** PREFERENCES ACTIONS ***/
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_UNITS = 'SET_UNITS';
export const SET_FAVORITES = 'SET_FAVORITES';
export const ADD_FAVORITE_CITY = 'ADD_FAVORITE_CITY';
export const REMOVE_FAVORITE_CITY = 'REMOVE_FAVORITE_CITY';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';

/*** WEATHER ACTIONS ***/

export const SET_CURRENT_LOCATION_WEATHER = 'SET_CURRENT_LOCATION_WEATHER';
export const SET_LOCATION_FORECAST = 'SET_LOCATION_FORECAST';
export const SET_AVAILABLE_CITIES = 'SET_AVAILABLE_CITIES';
export const SET_CITY_ID_MAP = 'SET_CITY_ID_MAP';
export const ADD_CITY_ID = 'ADD_CITY_ID';
